name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build ipxe firmware
        run: |
          make ipxe

      - name: Make build
        run: |
          make build

      - name: Upload artifact without images
        uses: actions/upload-artifact@v3
        with:
          name: go-pxe-installer-release-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: bin/*

      - name: Download images
        run: |
          make images

      - name: Make build with images
        run: |
          make buildi

      - name: Upload artifact with images
        uses: actions/upload-artifact@v3
        with:
          name: go-pxe-installer-with-images-release-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: bin/*
