name: Build and Release

on:
  push:
    tags:
      - 'v*-*'
  workflow_dispatch:
  repository_dispatch:
    types: [auto-release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Resolve tag
        id: resolve-tag
        run: |
          if [[ -n "${{ github.event.client_payload.ref }}" ]]; then
            TAG="${{ github.event.client_payload.ref }}"
          else
            TAG="${{ github.ref_name }}"
          fi
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v7
        with:
          ref: ${{ steps.resolve-tag.outputs.TAG }}

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.25

      - name: Build ipxe firmware
        run: |
          make ipxe

      - name: Make build
        run: |
          make build

      - name: Upload artifact without images
        uses: actions/upload-artifact@v7
        with:
          name: go-pxe-installer-${{ steps.resolve-tag.outputs.TAG }}-${{ runner.os }}-amd64
          path: bin/*

      - name: Download images
        run: |
          make images

      - name: Upload images checksum
        uses: actions/upload-artifact@v7
        with:
          name: checksum
          path: |
            *.checksum

      - name: Make build with images
        run: |
          make buildi

      - name: Upload artifact with images
        uses: actions/upload-artifact@v7
        with:
          name: go-pxe-installer-with-images-${{ steps.resolve-tag.outputs.TAG }}-${{ runner.os }}-amd64
          path: bin/*

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8.0.1

      - name: Tar artifacts
        run: |
          for dir in $(ls|grep go-pxe-installer)
          do
            tar -czpf $dir.tar.gz $dir
          done
          ls -al

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          files: "*.tar.gz"
          generate_release_notes: true
