name: Build and Release

on:
  push:
    tags:
      - 'v*-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build ipxe firmware
        run: |
          make ipxe

      - name: Make build
        run: |
          make build

      - name: Upload artifact without images
        uses: actions/upload-artifact@v3
        with:
          name: go-pxe-installer-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: bin/*

      - name: Download images
        run: |
          make images

      - name: Make build with images
        run: |
          make buildi

      - name: Upload artifact with images
        uses: actions/upload-artifact@v4
        with:
          name: go-pxe-installer-with-images-${{ github.ref_name }}-${{ runner.os }}-amd64
          path: bin/*

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7

      - name: Tar artifacts
        run: |
          for dir in $(ls)
          do
              tar -czpf $dir.tar.gz $dir
          done
          ls -al

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.tar.gz"
